# Generated by Django 3.1.1 on 2020-09-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_provider_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='rating',
        ),
    ]
